# Local lib: FBox data fetch and utils; login exported from fbox_login

from .fbox_login import (
    login,
    login_client_credentials,
    login_password,
    LOGIN_MODE_CLIENT_CREDENTIALS,
    LOGIN_MODE_PASSWORD,
    _has_user_credentials,
    get_token as get_token_from_config,
    ensure_token as ensure_token_from_config,
    with_fbox_token as with_fbox_token_factory,
)
from .fbox_client import (
    read_realtime_data,
    get_history_data_by_request,
    history_flatten,
    grouped_list_all_boxes,
    flat_list_all_boxes,
    get_box_single,
    get_dmon_groups,
    get_dmon_by_group,
    get_box_groups_and_data_points,
    get_box_data_points_history,
    get_boxes_location,
    timestamp_ms,
    boxes_get_history_params,
)

__all__ = [
    "login",
    "login_client_credentials",
    "login_password",
    "LOGIN_MODE_CLIENT_CREDENTIALS",
    "LOGIN_MODE_PASSWORD",
    "_has_user_credentials",
    "get_token_from_config",
    "ensure_token_from_config",
    "with_fbox_token_factory",
    "read_realtime_data",
    "get_history_data_by_request",
    "history_flatten",
    "grouped_list_all_boxes",
    "flat_list_all_boxes",
    "get_box_single",
    "get_dmon_groups",
    "get_dmon_by_group",
    "get_box_groups_and_data_points",
    "get_box_data_points_history",
    "get_boxes_location",
    "timestamp_ms",
    "boxes_get_history_params",
]
